# Generated by Django 2.0.7 on 2018-07-17 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=150)),
                ('activation_code', models.CharField(max_length=50)),
                ('redeemed', models.BooleanField(default=False)),
                ('lastsent', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, max_length=1000)),
                ('timestamp', models.DateTimeField()),
                ('isNsfw', models.BooleanField(default=False)),
                ('isSpoiler', models.BooleanField(default=False)),
                ('post_id', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('email', models.TextField(blank=True, max_length=50)),
                ('isActivated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
