# Generated by Django 2.0.7 on 2018-07-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180724_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isNsfw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='isSpoiler',
            field=models.BooleanField(default=False),
        ),
    ]
